//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace WebPortal.Models
{
    public interface IUserStatus
    {
        string Code { get; set; }
        string CreatedBy { get; set; }
        DateTime CreatedDate { get; set; }
        string Description { get; set; }
        bool IsDeleted { get; set; }
        string LastModifiedBy { get; set; }
        DateTime LastModifiedDate { get; set; }
        string Name { get; set; }
        int UserStatusId { get; set; }
    }
}